//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GK.Booking.WepApp.Domains.GK.Booking.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GK.Booking.WepApp.Domains.GK.Booking.Resources.Messages_RU", typeof(Messages_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция не разрешена для заказа с текущим статусом..
        /// </summary>
        internal static string CURRENT_STATUS_NOT_CORRECT_FOR_OPERATION {
            get {
                return ResourceManager.GetString("CURRENT_STATUS_NOT_CORRECT_FOR_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключено из экрана администратора..
        /// </summary>
        internal static string DISABLED_FROM_ADMIN_SCREEN {
            get {
                return ResourceManager.GetString("DISABLED_FROM_ADMIN_SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат номера телефона..
        /// </summary>
        internal static string INVALID_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("INVALID_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение не было отправлено..
        /// </summary>
        internal static string MESSAGE_NOT_SENT {
            get {
                return ResourceManager.GetString("MESSAGE_NOT_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время подтверждения заказа истекло..
        /// </summary>
        internal static string ORDER_EXPIRED {
            get {
                return ResourceManager.GetString("ORDER_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышено максимальное значение стоимости одного заказа..
        /// </summary>
        internal static string ORDER_MAXIMUM_PRICE_EXCEEDED {
            get {
                return ResourceManager.GetString("ORDER_MAXIMUM_PRICE_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказ не был создан..
        /// </summary>
        internal static string ORDER_NOT_CREATED {
            get {
                return ResourceManager.GetString("ORDER_NOT_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона заблокирован..
        /// </summary>
        internal static string PHONE_NUMBER_LOCKED {
            get {
                return ResourceManager.GetString("PHONE_NUMBER_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string sd {
            get {
                return ResourceManager.GetString("sd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный параметр конфигурации: {0}.
        /// </summary>
        internal static string SMS_INVALID_CONFIGURATION_PARAMETER {
            get {
                return ResourceManager.GetString("SMS_INVALID_CONFIGURATION_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [СМС Сервис]: Недостаточно средств на счёте..
        /// </summary>
        internal static string SMS_LOW_BALANCE {
            get {
                return ResourceManager.GetString("SMS_LOW_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранное время уже занято..
        /// </summary>
        internal static string TARGET_TIME_MAP_TRAY_IS_FULL {
            get {
                return ResourceManager.GetString("TARGET_TIME_MAP_TRAY_IS_FULL", resourceCulture);
            }
        }
    }
}
